"""
momentum.py — 動量交易策略 / Momentum Trading Strategy

基於 RSI 和 MACD 指標的趨勢跟蹤策略。
Trend-following strategy using RSI and MACD indicators.

Usage:
    strategy = MomentumStrategy(symbol="BTC/USDT", rsi_period=14)
    signal = strategy.generate_signal(ohlcv_data)
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from .base import BaseStrategy, BacktestResult, Signal


@dataclass
class MomentumConfig:
    """動量策略配置 / Momentum strategy configuration."""

    symbol: str = "BTC/USDT"
    timeframe: str = "1h"

    # RSI 設定 / RSI settings
    rsi_period: int = 14
    rsi_overbought: float = 70.0
    rsi_oversold: float = 30.0

    # MACD 設定 / MACD settings
    macd_fast: int = 12
    macd_slow: int = 26
    macd_signal: int = 9

    # 風控設定 / Risk settings
    stop_loss_pct: float = 2.0   # 止損百分比 / Stop-loss %
    take_profit_pct: float = 4.0  # 止盈百分比 / Take-profit %


class MomentumStrategy(BaseStrategy):
    """
    動量策略 — 使用 RSI + MACD 識別趨勢方向。
    Momentum Strategy — uses RSI + MACD to identify trend direction.

    Entry conditions:
        BUY  : RSI < oversold AND MACD histogram turns positive
        SELL : RSI > overbought AND MACD histogram turns negative
        HOLD : Otherwise
    """

    def __init__(self, config: MomentumConfig | None = None) -> None:
        self.config = config or MomentumConfig()
        self.name = "MomentumStrategy"

    # ──────────────────────────────────────────────
    # Public Interface
    # ──────────────────────────────────────────────

    def generate_signal(self, data: list[dict[str, Any]]) -> Signal:
        """
        根據最新 OHLCV 數據生成交易信號。
        Generate a trading signal from the latest OHLCV data.

        Args:
            data: List of OHLCV dicts with keys: time, open, high, low, close, volume

        Returns:
            Signal: BUY, SELL, or HOLD with metadata
        """
        if len(data) < self.config.macd_slow + self.config.macd_signal:
            return Signal(action="HOLD", reason="Insufficient data for indicators")

        closes = [float(c["close"]) for c in data]

        rsi = self._calc_rsi(closes, self.config.rsi_period)
        macd_line, signal_line, histogram = self._calc_macd(
            closes,
            self.config.macd_fast,
            self.config.macd_slow,
            self.config.macd_signal,
        )

        latest_rsi = rsi[-1]
        prev_hist = histogram[-2] if len(histogram) >= 2 else 0.0
        curr_hist = histogram[-1]

        # BUY 條件 / BUY condition
        if latest_rsi < self.config.rsi_oversold and curr_hist > 0 and prev_hist <= 0:
            return Signal(
                action="BUY",
                symbol=self.config.symbol,
                reason=f"RSI={latest_rsi:.1f} (oversold) + MACD histogram turned positive",
                stop_loss_pct=self.config.stop_loss_pct,
                take_profit_pct=self.config.take_profit_pct,
                metadata={"rsi": latest_rsi, "macd_hist": curr_hist},
            )

        # SELL 條件 / SELL condition
        if latest_rsi > self.config.rsi_overbought and curr_hist < 0 and prev_hist >= 0:
            return Signal(
                action="SELL",
                symbol=self.config.symbol,
                reason=f"RSI={latest_rsi:.1f} (overbought) + MACD histogram turned negative",
                stop_loss_pct=self.config.stop_loss_pct,
                take_profit_pct=self.config.take_profit_pct,
                metadata={"rsi": latest_rsi, "macd_hist": curr_hist},
            )

        return Signal(
            action="HOLD",
            symbol=self.config.symbol,
            reason=f"RSI={latest_rsi:.1f}, MACD_hist={curr_hist:.6f} — no clear signal",
            metadata={"rsi": latest_rsi, "macd_hist": curr_hist},
        )

    def execute(self, signal: Signal, market: dict[str, Any]) -> dict[str, Any]:
        """
        執行交易訂單（對接交易所 API）。
        Execute a trade order against the exchange API.

        Args:
            signal: Signal generated by generate_signal()
            market: Current market state dict (price, balance, etc.)

        Returns:
            Order result dict
        """
        if signal.action == "HOLD":
            return {"status": "skipped", "reason": "HOLD signal"}

        price = float(market.get("price", 0))
        balance = float(market.get("available_balance", 0))
        risk_amount = balance * (signal.stop_loss_pct / 100)
        # Size = dollar risk / dollar loss per unit if stop is hit
        size = round(risk_amount / (price * (signal.stop_loss_pct / 100)), 6)

        return {
            "status": "submitted",
            "strategy": self.name,
            "action": signal.action,
            "symbol": self.config.symbol,
            "size": size,
            "price": price,
            "stop_loss": price * (1 - signal.stop_loss_pct / 100) if signal.action == "BUY"
                         else price * (1 + signal.stop_loss_pct / 100),
            "take_profit": price * (1 + signal.take_profit_pct / 100) if signal.action == "BUY"
                           else price * (1 - signal.take_profit_pct / 100),
            "timestamp": datetime.utcnow().isoformat(),
        }

    def backtest(self, historical_data: list[dict[str, Any]]) -> BacktestResult:
        """
        對歷史數據執行回測。
        Run backtest on historical data.

        Args:
            historical_data: List of OHLCV dicts (chronological order)

        Returns:
            BacktestResult with performance metrics
        """
        trades: list[dict[str, Any]] = []
        position: dict[str, Any] | None = None
        equity = 10_000.0  # 初始資金 / Initial capital

        min_bars = self.config.macd_slow + self.config.macd_signal + 1

        for i in range(min_bars, len(historical_data)):
            window = historical_data[: i + 1]
            signal = self.generate_signal(window)
            price = float(historical_data[i]["close"])

            if signal.action == "BUY" and position is None:
                size = equity * 0.95 / price
                position = {"entry_price": price, "size": size, "entry_idx": i}

            elif signal.action == "SELL" and position is not None:
                pnl = (price - position["entry_price"]) * position["size"]
                equity += pnl
                trades.append({
                    "entry": position["entry_price"],
                    "exit": price,
                    "size": position["size"],
                    "pnl": round(pnl, 2),
                    "pnl_pct": round((price / position["entry_price"] - 1) * 100, 2),
                })
                position = None

        total_pnl = sum(t["pnl"] for t in trades)
        winning = [t for t in trades if t["pnl"] > 0]
        return BacktestResult(
            strategy=self.name,
            total_trades=len(trades),
            winning_trades=len(winning),
            total_pnl=round(total_pnl, 2),
            total_return_pct=round((equity / 10_000.0 - 1) * 100, 2),
            win_rate=round(len(winning) / len(trades) * 100, 2) if trades else 0.0,
            final_equity=round(equity, 2),
        )

    # ──────────────────────────────────────────────
    # Private helpers
    # ──────────────────────────────────────────────

    @staticmethod
    def _calc_rsi(closes: list[float], period: int) -> list[float]:
        """Calculate RSI for a list of closing prices."""
        if len(closes) < period + 1:
            return [50.0] * len(closes)

        deltas = [closes[i] - closes[i - 1] for i in range(1, len(closes))]
        gains = [max(d, 0.0) for d in deltas]
        losses = [abs(min(d, 0.0)) for d in deltas]

        avg_gain = sum(gains[:period]) / period
        avg_loss = sum(losses[:period]) / period

        rsi_values: list[float] = [50.0] * (period + 1)
        for i in range(period, len(deltas)):
            avg_gain = (avg_gain * (period - 1) + gains[i]) / period
            avg_loss = (avg_loss * (period - 1) + losses[i]) / period
            rs = avg_gain / avg_loss if avg_loss != 0 else (float("inf") if avg_gain > 0 else 1.0)
            rsi_values.append(100 - 100 / (1 + rs))

        return rsi_values

    @staticmethod
    def _ema(values: list[float], period: int) -> list[float]:
        """Calculate Exponential Moving Average."""
        if not values:
            return []
        k = 2.0 / (period + 1)
        ema = [values[0]]
        for v in values[1:]:
            ema.append(v * k + ema[-1] * (1 - k))
        return ema

    def _calc_macd(
        self,
        closes: list[float],
        fast: int,
        slow: int,
        signal_period: int,
    ) -> tuple[list[float], list[float], list[float]]:
        """Calculate MACD line, signal line, and histogram."""
        ema_fast = self._ema(closes, fast)
        ema_slow = self._ema(closes, slow)

        macd_line = [f - s for f, s in zip(ema_fast, ema_slow)]
        signal_line = self._ema(macd_line, signal_period)
        histogram = [m - s for m, s in zip(macd_line, signal_line)]

        return macd_line, signal_line, histogram
